### ISSUE TITLE
Update acknowledgment instructions to reflect emerging software citation best practices

### ISSUE THREAD

**Issue by namurphy** [astropy/astropy#11268]
An [emerging best practice for software citation]() is to cite the _specific version_ of a software package, rather than only citing a journal article, website, or a continually changing code repository.  For example, if I wanted to cite Astropy version 3.1, then I would cite the [Astropy 3.1 Zenodo record](http://doi.org/10.5281/zenodo.4080996) and include the DOI of `10.5281/zenodo.4080996` to provide a persistent identifier that uniquely identifies which version of the software was used for a project.

I propose that we update the citation instructions to reflect this emerging best practice by requesting that authors cite (1) the Zenodo record for the relevant Astropy release, and (2) the 2013 & 2018 papers.  The information on the `\software` macro for AASTeX and the sentence in the acknowledgments would need to be updated to include both the software & journal citations but otherwise wouldn't need to change.  (This could also involve updating `astropy.__citation__` to be the Zenodo record, though this would require reserving the DOI for the next Astropy version ahead of time and updating it there ahead of the release...which is something that could easily be forgotten.  I'm not sure what's best here.)

For more information on this I'd suggest the article

 - D. Bouquin et al. (2020, ApJ), [_Credit Lost: Two Decades of Software Citation in Astronomy_](https://doi.org/10.3847/1538-4365/ab7be6)
 - [Interview with Daina Bouquin about this paper](https://www.youtube.com/watch?v=iuEtZC2Ir-A&t=117s)
 - [AAS Journals Policy Statement on Software](https://journals.aas.org/news/policy-statement-on-software/)

We updated the [software citation policy for PlasmaPy](https://docs.plasmapy.org/en/stable/about/citation.html) in response to the Bouquin et al. paper.  That paper also talks about the serious disadvantages of using a journal article citation as the proxy for a software citation (e.g., people who contributed to the package after then aren't listed as authors, ambiguity about which version of the software was actually used which reduces reproducibility, and papers becoming out-of-date compared to more recent versions of the software).

**Comment by namurphy** [comment]
Oh...and these changes should be done after #10611 is closed, since the more recent Zenodo releases aren't up there yet.  Thanks!

**Comment by pllim** [comment]
cc @adrn @jdswinbank @eteq 

Thanks! I milestoned this to 4.3 because I think this is important to be sorted out before the next major release.

**Comment by hamogu** [comment]
Sherpa recently added a function to query Zenodo for a specific version: https://github.com/sherpa/sherpa/blob/master/sherpa/__init__.py#L658
That way, the DOI does not have to be known at release time, instead it can be queried on the fly (with internet access). Older releases are hardcoded as backup in case no internet connection is available. I'm sure this code could be adapted for astropy (not copied, because sherpa is GPL licenced, while astropy is MIT licensed - but we could ask @DougBurke, the author of the Sherpa function, to re-license this specific function under an MIT license for inclusion in astropy.)

**Comment by DougBurke** [comment]
The zenodo api is relatively simple - just HTTP calls - but you do have to deal with paging the results (which the Sherpa code didn't initially). There may even be a python package for zenodo (but it may not be worth pulling in as a dependency).

https://sherpa.readthedocs.io/en/latest/developer/index.html#update-the-zenodo-citation-information is my attempt to document the process for a new release.

Let me know if you are interested in re-licensing this part of Sherpa.

**Comment by pllim** [comment]
It was my bad to milestone an issue. I don't think I should have done that, so removing now.

**Comment by adrn** [comment]
I do think this is high priority and we should make sure at minimum that a v4.3 record gets added to zenodo...

**Comment by adrn** [comment]
Currently, our acknowledging and citing page is on the main astropy.org site, which means it is a static HTML page served by github pages. That means that, with our current infrastructure, we would have to manually update the latest zenodo record with each release. I think ideally we want to provide the bibtex entry for the latest Zenodo record and have it track the latest release automatically. Similar to the suggestions above, I just implemented this for one of my maintained packages, but it is part of the docs build: I added this to `conf.py`:

```python
zenodo_path = pathlib.Path('ZENODO.rst')
if not zenodo_path.exists():
    import textwrap
    try:
        import requests
        headers = {'accept': 'application/x-bibtex'}
        response = requests.get('https://zenodo.org/api/records/4159870',
                                headers=headers)
        response.encoding = 'utf-8'
        zenodo_record = (".. code-block:: bibtex\n\n" +
                         textwrap.indent(response.text, " "*4))
    except Exception as e:
        warnings.warn(f"Failed to retrieve Zenodo record for Gala: {str(e)}")
        zenodo_record = ("`Retrieve the Zenodo record here "
                         "<https://zenodo.org/api/records/4159870>`_")

    with open(zenodo_path, 'w') as f:
        f.write(zenodo_record)
```

And then include this on my "Citation" page:
```
.. include:: ZENODO.rst
```

So, a question for all: Do we want to move the citation and acknowledging page into the documentation and link from astropy.org? Or do the manual updates? Or make website build, rather than static?

**Comment by pllim** [comment]
> a v4.3 record gets added to zenodo

I think @eteq got the webhook to work but alas that created a new DOI. I am still not sure what is the solution here, maybe @eteq or @mwcraig have updates.

**Comment by adrn** [comment]
Interesting - I do see a v4.2.1 record but yes, it's under a different DOI... 

previous versions (up to v3.1): https://zenodo.org/record/4080996
v4.2.1: https://zenodo.org/record/4670729

**Comment by DougBurke** [comment]
It's at this point that I bring in @augustfly to the discussion as he has worked on this/been brought into this because of me for other projects.

Zenodo explicitly has different DOIs for each release, and there is a "general" DOI for the project but I don't know what the latest information is on attempts to identify the latest version. I believe that Zenodo lets you pre-register a DOI for a release, which might be useful for a "create the docs" system but I don't know if you can actually do anything with that DOI until there's been a release. https://github.com/codemeta/codemeta/issues/167 has some related - but not directly relevant - discussions.
