### ISSUE TITLE
Version 5.3 fails to read large CompImageHDUs

### ISSUE THREAD

**Issue by alagg** [astropy/astropy#15482]
### Description

Large FITS files with produced with the JSOC mtrack module ([http://hmi.stanford.edu/rings/modules/mtrack.html](http://hmi.stanford.edu/rings/modules/mtrack.html)) cannot be read with astropy 5.3.0--5.3.4. 

The issue occurs only when the fits file contains a large CompImageHDU. In the example below, the data of size [641,1700,1700] are stored using the `HCOMPRESS_1` compression method. But also other compression methods (e.g. `RICE`) share the same issue.

### Expected behavior

There should be no coredump (segmentation fault) when accessing the data in the CompImageHDU.

### How to Reproduce

1. Download the sample file from my Dropbox (2.7 Gbyte): [Vcomp.fits](https://www.dropbox.com/scl/fi/m1jruw8esipdtsh4vkh82/Vcomp.fits?rlkey=k5svmo3hdigoslk9ty0t1ajsm&dl=1).
2. Open the file, and try to access the CompImageHDU:
```
from astropy.io import fits

hdu = fits.open('Vcomp.fits')
shape = hdu[1].data.shape
```
3. With astropy 5.3.x I get the following error:
```
zsh: segmentation fault  ipython

/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
4.  The error could be reproduced on MacOS 14, python version 3.11, and on 2 different linux workstations (x86_64 architecture) with python 3.9--3.12 (see example configurations in the version section below).
5. There is no problem when reading in the file with astropy 5.1 or 5.2.  
6. There's no proble for smaller files produced with the same mtrack tool (e.g. 50 frames instead of 641 frames).

### Versions

macOS-14.0-arm64-arm-64bit
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
astropy 5.3.4

Linux-4.18.0-372.70.1.1.el8_6.x86_64-x86_64-with-glibc2.28
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
astropy 5.3

**Comment by pllim** [comment]
cc @astrofrog @Cadair 

p.s. Segmentation fault sounds pretty serious. Are you able to get more traceback using `gdb`?

**Comment by alagg** [comment]
More info is provided by the "Problem Report for Python" window that pops up on my macbook when the segmentation fault occurs. I attach the problem report:
[segfault.log](https://github.com/astropy/astropy/files/12907008/segfault.log)

The terminal shows the following output:
```
zsh: segmentation fault  python segfault.py
(venv) lagg@lagan-tm22 .../FD_test/> /opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Hope this helps.
Unfortunately, I do not know how to use `gdb` to produce a traceback, sorry.

**Comment by pllim** [comment]
This lines that jump out to me are the following but hopefully `io.fits` devs have more ideas. Thanks!

```
2   _compression.cpython-311-darwin.so	       0x1040f6d80 fits_rdecomp_short + 1412
3   _compression.cpython-311-darwin.so	       0x1040e4240 decompress_rice_1_c + 256
```

**Comment by saimn** [comment]
Interestingly ds9 also segfaults:
```
❯ ds9 Vcomp.fits 
[1]    303833 segmentation fault (core dumped)  ds9 Vcomp.fits
```

More info with faulthandler:
```
❯ python -X dev                                
Python 3.12.0 (main, Oct  5 2023, 22:42:34) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.io import fits
>>> 
>>> hdu = fits.open('Vcomp.fits')
>>> hdu.info()
Filename: Vcomp.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   ()      
  1  COMPRESSED_IMAGE    1 CompImageHDU     11   (1700, 1700, 641)   int16   
>>> shape = hdu[1].data.shape
Fatal Python error: _PyMem_DebugMalloc: Python memory allocator called without holding the GIL
Python runtime state: initialized

Current thread 0x00007fe01c997740 (most recent call first):
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_codecs.py", line 277 in decode
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_tiled_compression.py", line 49 in _decompress_tile
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_tiled_compression.py", line 430 in decompress_image_data_section
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/section.py", line 54 in __getitem__
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/compressed.py", line 579 in data
  File "/home/simon/dev/astropy/astropy/astropy/utils/decorators.py", line 837 in __get__
  File "<stdin>", line 1 in <module>
```

The "memory allocator called without holding the GIL" error seems caused by the nogil block here:
https://github.com/astropy/astropy/blob/d64fc339429487631173fc5f81dd0130cc54fa3d/astropy/io/fits/hdu/compressed/src/compression.c#L261-L279

So I tried without `Py_BEGIN_ALLOW_THREADS`/`Py_END_ALLOW_THREADS` and it fixes the segfault but I get another error.
```
>>> shape = hdu[1].data.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/dev/astropy/astropy/astropy/utils/decorators.py", line 837, in __get__
    val = self.fget(obj)
          ^^^^^^^^^^^^^^
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/compressed.py", line 579, in data
    data = self.section[...]
           ~~~~~~~~~~~~^^^^^
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/section.py", line 54, in __getitem__
    data = decompress_image_data_section(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_tiled_compression.py", line 430, in decompress_image_data_section
    tile_buffer = _decompress_tile(
                  ^^^^^^^^^^^^^^^^^
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_tiled_compression.py", line 49, in _decompress_tile
    return ALGORITHMS[algorithm](**settings).decode(buf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/dev/astropy/astropy/astropy/io/fits/hdu/compressed/_codecs.py", line 277, in decode
    dbytes = decompress_rice_1_c(
             ^^^^^^^^^^^^^^^^^^^^
_compression.CfitsioException: decompression warning: unused bytes at end of compressed buffer
```

Ok, I was confused by the issue because `malloc` shouldn't be a problem here, but the Python error comes from the use of `PyErr_SetString` in `ffpmsg`, will open a PR.
This doesn't solve the decompression warning, which can maybe be turned into a warning ?

**Comment by Cadair** [comment]
>  This doesn't solve the decompression warning, which can maybe be turned into a warning ?

Does that mean that cfitsio doesn't like the file or we have fed it too many bytes?

**Comment by saimn** [comment]
Not sure if it's a problem with the file or the way we parse it (and I haven't checked with astropy<5.3) , but if I just print the messages from cfitsio without setting the exception I get this:
```
In [3]: hdu[1].data[0]
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression warning: unused bytes at end of compressed buffer
decompression warning: unused bytes at end of compressed buffer
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
decompression error: hit end of compressed byte stream
Out[3]: 
array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [1306.5, 1307.5, 1308. , ..., 1395. , 1401.5, 1407.5],
       [ 840. ,  847. ,  854.5, ..., 1314. , 1314.5, 1315. ],
       [1492. , 1495. , 1498.5, ..., 1335.5, 1335. , 1335. ]],
      dtype=float32)

In [4]: hdu[1].data[0].shape
Out[4]: (1700, 1700)
```

**Comment by saimn** [comment]
```
In [1]: %astropy
Numpy 1.26.0
Astropy 5.2.3.dev0+g32d49b9600.d20231017

In [2]: hdu = fits.open('Vcomp.fits')

In [3]: hdu[1].data[0]
Out[3]: 
array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [1306.5, 1307.5, 1308. , ..., 1395. , 1401.5, 1407.5],
       [ 840. ,  847. ,  854.5, ..., 1314. , 1314.5, 1315. ],
       [1492. , 1495. , 1498.5, ..., 1335.5, 1335. , 1335. ]],
      dtype=float32)
```
So those warnings/errors where just ignored ? :scream:

**Comment by alagg** [comment]
> ```
> In [1]: %astropy
> Numpy 1.26.0
> Astropy 5.2.3.dev0+g32d49b9600.d20231017
> 
> In [2]: hdu = fits.open('Vcomp.fits')
> 
> In [3]: hdu[1].data[0]
> Out[3]: 
> array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
>        [   nan,    nan,    nan, ...,    nan,    nan,    nan],
>        [   nan,    nan,    nan, ...,    nan,    nan,    nan],
>        ...,
>        [1306.5, 1307.5, 1308. , ..., 1395. , 1401.5, 1407.5],
>        [ 840. ,  847. ,  854.5, ..., 1314. , 1314.5, 1315. ],
>        [1492. , 1495. , 1498.5, ..., 1335.5, 1335. , 1335. ]],
>       dtype=float32)
> ```
> 
> So those warnings/errors were just ignored ? 😱

The NANs in the data are not an error, they are part of the data: The data contain velocity maps of the solar disk (in a plate carree projection, i.e. in equal longitude and latitude bins), and the NAN values are indicating pixels lying outside the solar disk.

**Comment by saimn** [comment]
I don't know if NaNs are the problem, they should be supported AFAIK.

But this is getting funny, `hdul[1].data[600]` works (reading the full array after dealing with GIL issue, e.g. #15489), but `hdul[1].section[600]` segfaults...

**Comment by saimn** [comment]
Ok, so there is a problem with this file: the compressed data is stored in a vla column with `TFORM='1PB(3982029)'`, but `P` means an int32 that cannot store correctly the offsets beyond some limit. When reaching plane 533 (in the first dimension) the offset reaches the maximum of an int32 and becomes negative... leading to undefined behavior, reading random bytes somewhere, causing the warnings and errors we saw above, or segfaults with `.section` (not sure why the behavior differs).
Interestingly fitsio is happy when reading planes > 533, so maybe cfitsio detects and corrects the issue silently ? Which would explains why astropy<5.3 was happy too.
Now the question is, what do we do ? Fix the column type (P → Q) but this means computing the heap size and detecting overflow etc., or raise an error if the offset is negative. @Cadair @astrofrog

**Comment by alagg** [comment]
Thanks for identifying the issue! Great work!
I contacted the developers of the mtrack software package, and hope that they can set the correct column type when creating the file.
However,  I think it is important that a faulty file should not result in a segmentation fault, but by raising an exception. It would be great if the issue could be corrected 'on the fly'.
Is a negative offset really sufficient to detect the error? What if the offset is so large that the int32 boundary is hit 2x, resulting in a wrong but positive offset?

**Comment by alagg** [comment]
I reported the issue to the developers of the drms package which produced this fits file. Here the reply by Keh-Cheng Chu (Stanford), which might help in a decision on how to proceed further:

"CFITSIO uses 64-bit integers internally to handle variable length arrays
regardless of whether the descriptor is P or Q.  When it writes a
compressed FITS file, it will use the P descriptor if the uncompressed
size of the array is less than 4GB (not 2GB) or the Q descriptor if
the uncompressed size is over 4GB.  I think this behavior is consistent
with the FITS Standard, which says that the P(Q) descriptor is a 32(64) bit
integer, and that "the meaning of a negative value of either of these
integers is not defined by this standard."  Clearly CFITSIO took advantage
of the ambiguity in the standard to allow a P value between 2^31 and 2^32.
Astropy must have done similar things in earlier versions, so I don't
understand why they made the change in recent versions.  Is it
for stricter conformance to the standard?  But the standard doesn't
disallow the old behavior!"

**Comment by saimn** [comment]
Well previously astropy was using cfitsio to do all the tile decompression. But I disagree with the interpretation above, the Standard says:
> What is stored
in the main data table field is an array descriptor. This consists
of two 32-bit signed integer values in the case of ’P’ array de-
scriptors, or two 64-bit signed integer values in the case of ’Q’
array descriptors: the number of elements (array length) of the
stored array, followed by the zero-indexed byte offset of the first
element of the array, measured from the start of the heap area.
The meaning of a negative value for either of these integers is
not defined by this Standard.

Note the 32-bit **signed** integer so the limit is 2Gb and not 4Gb, and undefined behavior also means that reading random bytes and returning junk is allowed, and segfault also is ;).

**Comment by saimn** [comment]
Forgot to say thanks @alagg for contacting them, it helps understanding the origin of the issue :)
I guess we could fix the offset, it's just that it requires more work, and it's annoying to loose time and have to deal with deviations from the Standard (especially when it comes from cfitsio itself).

**Comment by alagg** [comment]
> Forgot to say thanks @alagg for contacting them, it helps understanding the origin of the issue :) I guess we could fix the offset, it's just that it requires more work, and it's annoying to loose time and have to deal with deviations from the Standard (especially when it comes from cfitsio itself).

No need to thank - in the end it's me who caused all this :-)

**Comment by Cadair** [comment]
Does all this mean we could generate a file with this "issue" using fitsio in Python as a test?

**Comment by Cadair** [comment]
Also, perhaps we should report this to cfitsio?

**Comment by saimn** [comment]
Segfault with the GIL is fixed but not the P/Q issue.
Yes I guess we could generate a file but it would have to be big in order to have negative offsets. We already have a few similar tests that are skipped by default, so can be done.

**Comment by alagg** [comment]
Thanks for the efforts!
How can I download and test the segfault-fixed version?

**Comment by pllim** [comment]
You could install from source or wait a day to get the nightly wheel.

https://docs.astropy.org/en/latest/install.html#building-from-source

https://docs.astropy.org/en/latest/install.html#installing-pre-built-development-versions-of-astropy

**Comment by alagg** [comment]
I could test the nightly wheel and indeed the segfault is gone. Instead, it now raises a cfitsio exception:
```
_compression.CfitsioException: decompression warning: unused bytes at end of compressed buffer
```
which I can catch and prevent my code to exit unexpectedly.

However, the issue remains that CFITSIO produces fits files which cannot be read with `astropy.io.fits`. There might not be many of such files around in various data bases, but it's likely that there are some, so it is necessary that also astropy must be able to read those files, even if they were produced with a cfitsio version violating the standard (or interpreting the 'ambiguity' in the standard in a certain way).

I think it is important to discuss this issue with the cfitsio people and to agree on a solution. If I can be of any help in this process, I'd be happy to do so.

**Comment by saimn** [comment]
Last time I missed that section in the Standard:
![image](https://github.com/astropy/astropy/assets/311639/685b0e98-9d53-41ca-8420-aaf35d8bbe7d)
which leaves no ambiguity.
@alagg - Any help is welcome and it would be good to report the issue to cfitsio indeed, so if you want to do it please go ahead :)

Note that the main source of segfault if fixed, but the code still reads at random positions which can still cause a segfault, in particular when using `.section`.

**Comment by alagg** [comment]
I wrote to the cfitsio helpdesk (see attached mail). Let's see what happens. I'll keep you posted...
[cfitsio.txt](https://github.com/astropy/astropy/files/13066380/cfitsio.txt)

**Comment by mhvk** [comment]
Flexible on input, strict on output would suggest to use unsigned int on input, but not write such files ourselves.

**Comment by alagg** [comment]
In the last issue of the fitsbist mailing list Bill Pence wrote a message about this issue. Here the article:
[fitsbits Digest, Vol 148, Issue 2.txt](https://github.com/astropy/astropy/files/13205505/fitsbits.Digest.Vol.148.Issue.2.txt)

**Comment by alagg** [comment]
I found that in the CFITSIO description this issue is explicitely mentioned (see [](https://heasarc.gsfc.nasa.gov/fitsio/c/c_user/node29.html)). There it reads:

> The 'P' type variable length columns use 32-bit array length and byte offset values, whereas the 'Q' type columns use 64-bit values, which may be required when dealing with large arrays. CFITSIO supports a local convention that interprets the 'P' type descriptors as unsigned 32-bit integers, which provides a factor of 2 greater range for the array length or heap address than is possible with 32-bit 'signed' integers. Note, however, that other software packages may not support this convention, and may be unable to read thees extended range variable length records.

I still think that also astropy should accept that, and as @mhvk wrote, be "Flexible on input, strict on output". It would be great if this convention could make it into astropy.

**Comment by pllim** [comment]
@astrofrog is this still relevant after the compressed FITS refactoring?

**Comment by saimn** [comment]
yes still an issue, to be fixed on our side.
