### ISSUE TITLE
`io.fits` does not support `NULL` values for Logical ('L') data

### ISSUE THREAD

**Issue by kYwzor** [astropy/astropy#18815]
### Description

This relates to #18755 but it's a separate issue as that one is focused on a specific issue with VLAs, while this one applies to all types of L columns.

Logical data is one of the data types allowed in FITS binary tables, represented by the `TFORMn` value `'L'`. According to the FITS specification:

> If the value of the TFORMn keyword specifies Data Type ’L’, the contents of Field n shall consist of ASCII T indicating true or ASCII F, indicating false. A 0 byte (hexadecimal 00) indicates a NULL value.

However, the `NULL` value is impossible to write or read via `io.fits`. 

### Expected behavior

Being able to have logical columns containing NULL values via `io.fits`, as supported by the FITS specification.

### How to Reproduce

In this script I first try to write a NULL value by using `io.fits` and a data array containing `None` and then I print the results. Then I try to achieve the same via `table.Table` using `np.ma.masked`. Finally, I explicitly edit the file to change the first logical byte to `b'\0'` and try to read it with both `io.fits` and `table.Table`.

```python
import numpy as np

from astropy.io import fits
from astropy.table import Table

testfile = "testfile.fits"

col = fits.Column(name="a", format="L", array=[None, False, True])
tab = fits.BinTableHDU.from_columns(name="test", columns=[col])
tab.writeto(testfile, overwrite=True)
print(fits.getdata(testfile))

t_w = Table(rows=[[np.ma.masked],[False],[True]],names=["a"])
t_w.write(testfile, overwrite=True)
print(Table.read(testfile))

# Edit file to explicitly change the first logical byte to 0
with open(testfile, "rb+") as f:
    f.seek(5760)
    f.write(b'\0')

print(fits.getdata(testfile))
print(Table.read(testfile))
```

The output is:
```
[( 1,) ( 0,) ( 1,)]
  a  
-----
 True
False
 True
[( 0,) ( 0,) ( 1,)]
  a  
-----
False
False
 True
```

Essentially, whether we use `None` and write with `io.fits` or `np.ma.masked` and write via `table.Table`, the `NULL` value is always written as `True`. If we explicitly set the first logical byte to 0, it is interpreted as `False`

### Versions

```python
import astropy
astropy.system_info()
```
```
platform
--------
platform.platform() = 'Windows-10-10.0.19045-SP0'
platform.version() = '10.0.19045'
platform.python_version() = '3.13.2'
packages
--------
astropy              7.1.dev839+g8ce617a04b
numpy                2.2.4
scipy                1.15.2
matplotlib           3.10.1
pandas               2.3.3
pyerfa               2.0.1.5
```

**Comment by aviralgarg05** [comment]
I would like to solve this issue

**Comment by aakash-priyadarshi** [comment]
Hi @aviralgarg05 and @kYwzor!

I just finished working on #18778 which fixes logical VLAs (PL/QL formats). I'm familiar with the logical data conversion code now.

I noticed #18815 is for fixed-width logical columns (L format), which is related but uses different code paths. Since I already understand this area of the codebase, I'd be happy to collaborate on this issue.

@aviralgarg05 - Are you actively working on this? Would you like to collaborate, or would you prefer to handle it yourself? Happy to help either way!

**Comment by ZenthWolf** [comment]
I have an attempt to fix this, but I hit a snag with unit testing. I based my work on @aakash-priyadarshi 's PR, which uses dtype=object, but this breaks over 40 units tests mostly due to the dtype transition- the tests for fixed-length arrays are much more strict about this, and I do not know if I should be the one to review the tests.

The tests themselves may be a barrier making this a bigger deal than expected.

You can see the implementation on my fork: https://github.com/ZenthWolf/astropy/tree/logical-null-handling

I did not think to send this as a PR because of the unit tests- if it would be more accessible that way, let me know how to mark it neatly as a WIP.

**Comment by pllim** [comment]
@ZenthWolf it is tough to review without a PR open. If it is not ready, you can open a *draft pull request* instead. Thanks!

https://github.blog/news-insights/product-news/introducing-draft-pull-requests/

**Comment by ZenthWolf** [comment]
Draft is up #18839, and I found a bug in my implementation dropping the unit test issues down to about 10, and found some issues with printing and masked_columns.

I think we need some consensus if `np.bool` is still desirable or not. From @aakash-priyadarshi's PR, a couple of tests are failed currently. Existing unit tests expected `np.bool` types, so in my approach I shifted to that, but ended introducing a couple of failures as a result. I also need to dig in on why we ended up mismatching dtypes:

`
FAILED astropy/io/fits/tests/test_logical_vla.py::test_logical_vla_empty_string_input - assert np.True_ is True
FAILED astropy/io/fits/tests/test_logical_vla.py::test_fixed_width_logical_roundtrip - AssertionError: assert (dtype('O') == dtype('bool') or dtype('O') == bool)
`

**Comment by saimn** [comment]
I appreciate the enthusiasm for creating PRs but maybe we should a bit before about how to fix the issue (or even if we want to fix it). 
The problem is that there is no way to store a NULL value in a Numpy bool array. And `io.fits` is not using masked arrays. And we cannot change things to use an object array.
So before thinking about supporting this nice feature, I would rather like to know if this is used in the wild, and if other libraries are supporting it (fitsio, cfitsio etc.).

**Comment by astrofrog** [comment]
@saimn - I did some investigating, and here's an example that first creates a file which has a logical column with ``True, NULL, False`` and then tries to read it in with io.fits, Table (which sometimes does extra stuff), and fitsio:

```python
import numpy as np
import fitsio
from astropy.table import Table
from astropy.io import fits as astropy_fits

path = 'logical_null_test.fits'

# Create file with astropy.io.fits
col = astropy_fits.Column(name='flag', format='L', array=[True, True, False])
hdu = astropy_fits.BinTableHDU.from_columns([col])
hdu.writeto(path, overwrite=True)

# Patch the file to insert a NULL byte for the middle value
with open(path, 'rb') as f:
    content = bytearray(f.read())

idx = content.find(b'TTF')
if idx >= 0:
    print(f"Found TTF at offset {idx}, replacing middle T with NULL (0x00)")
    content[idx + 1] = 0x00
    with open(path, 'wb') as f:
        f.write(content)

# Verify the raw bytes
with open(path, 'rb') as f:
    content = f.read()
idx = content.find(b'T\x00F')
if idx >= 0:
    print(f"Verified: raw bytes are {list(content[idx:idx+3])} (84='T', 0=NULL, 70='F')")

print("\n--- Reading back ---\n")

# 1. Read with astropy.io.fits (low-level)
print("1. astropy.io.fits:")
with astropy_fits.open(path) as hdul:
    data = hdul[1].data
    print(f"   Data: {data['flag']}")

# 2. Read with astropy Table
print("\n2. astropy Table:")
astropy_result = Table.read(path)
print(f"   Data: {list(astropy_result['flag'])}")

# 3. Read with fitsio
print("\n3. fitsio:")
with fitsio.FITS(path) as fits:
    fitsio_result = fits[1].read()['flag']
    print(f"   Data: {fitsio_result}")
```

The output is:

```
Found TTF at offset 5760, replacing middle T with NULL (0x00)
Verified: raw bytes are [84, 0, 70] (84='T', 0=NULL, 70='F')

--- Reading back ---

1. astropy.io.fits:
   Data: [ True False False]

2. astropy Table:
   Data: [np.True_, np.False_, np.False_]

3. fitsio:
   Data: [ True False False]
```

All three return ``False`` where the file has ``NULL``. If I then try and read in this file with CFITSIO:

```C
#include <stdio.h>
#include "fitsio.h"

int main(void) {
    fitsfile *fptr;
    int status = 0;
    char values[3];
    char nullflags[3];
    int anynul;

    fits_open_file(&fptr, "logical_null_test.fits", READONLY, &status);
    if (status) {
        fits_report_error(stderr, status);
        return 1;
    }

    fits_movabs_hdu(fptr, 2, NULL, &status);  // Move to first extension

    // Read logical column with null flags (ffgcfl)
    ffgcfl(fptr, 1, 1, 1, 3, values, nullflags, &anynul, &status);
    if (status) {
        fits_report_error(stderr, status);
        return 1;
    }

    printf("cfitsio reads logical column with NULL support:\n\n");
    for (int i = 0; i < 3; i++) {
        if (nullflags[i]) {
            printf("  Row %d: NULL\n", i + 1);
        } else if (values[i]) {
            printf("  Row %d: TRUE\n", i + 1);
        } else {
            printf("  Row %d: FALSE\n", i + 1);
        }
    }

    printf("\nRaw values array: [%d, %d, %d]\n", values[0], values[1], values[2]);
    printf("Null flags array: [%d, %d, %d]\n", nullflags[0], nullflags[1], nullflags[2]);

    fits_close_file(fptr, &status);
    return 0;
}
``` 

this outputs:

```
cfitsio reads logical column with NULL support:

  Row 1: TRUE
  Row 2: NULL
  Row 3: FALSE

Raw values array: [1, 0, 0]
Null flags array: [0, 1, 0]
```

**Comment by pllim** [comment]
Fixed in #19374

**Comment by kYwzor** [comment]
Sorry for the late reaction. While #19374 is great to see and solves part of the issue, I do not believe it fixes every problem described in this issue. Specifically, it only addresses _reading_ files with `NULL` values via `astropy.io.fits`. I've played around with that branch, the following issues remain:

1. It's still not possible to read files with `NULL` values via `astropy.io.table`. Attempting to do `Table.read` on a file containing `NULL` values results in a warning (`WARNING: Column 'a' contains NULL (undefined) values which will be converted to False. To preserve NULL information, reopen the file with logical_as_bytes=True and check for bytes values of b'\x00' (NULL), b'T' (True), and b'F' (False). [astropy.io.fits.fitsrec]`) and the NULL values are indeed interpreted as false (rather than as a masked value). Attempting to use the suggested option `logical_as_bytes=True` in `Table.read` results in `TypeError: read_table_fits() got an unexpected keyword argument 'logical_as_bytes'` (the parameter is only designed for `astropy.io.fits`, so the warning is a bit misleading). Ideally `astropy.io.table` would probably deal with this via `logical_as_bytes` internally, and handle the conversion to logical values / masking by itself.
2. It's still not possible to write a logical column with `NULL` values via either `astropy.io.fits` or `astropy.io.table`. Attempting to do so via a `None` value or a masked array (respectively) results in a silent conversion from `None`/masked to `True`.
3. If you do `a = fits.getdata(testfile, logical_as_bytes=True)` on a file that contains NULL values, and then attempt to do `print(a)` you get an exception: `ValueError: Unknown format code 'd' for object of type 'str'`. It seems `__str__` is broken, though `__repr__` works fine.

I'd consider reopening this issue, or at least it might be worth it to create separate issues for the remaining problems.

EDIT: Ok I think point 2. is actually now being addressed in #19694 if I understand it correctly.
