### ISSUE TITLE
test failures on 32bit linux

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#3380]
There are a 11 test failures when I test the master on an old 32bit system. 

Some of the fails seem genuine, e.g. 
- we don't say in the docs which `scipy` version is required, or check for the version in the test, and obviously 0.10.0 is not enough for the coordinates module
- error of `TypeError: data type "float128" not understood`
- `TypeError: 'buffer' does not have the buffer interface` at several places in relation with `io.fits`

Full log: https://gist.github.com/bsipocz/38a4d6bf5041d837a2f8

**Comment by embray** [comment]
Hmm.  It's too late to do this for v1.0 I think.  But maybe for v2.0 we should consider dropping support for 32-bit altogether?  Would that even be feasible?  In the meantime these should be fixed or worked around...

**Comment by bsipocz** [comment]
I'm fixing the first one as it's not related to 32bit or 64bit, but how we handle it if only an old version is available from scipy. 

However I run into weird stuff with the testing environment which may end up in another issue if I can't figure out how to make it work.

**Comment by embray** [comment]
I'll take a look at the FITS and modeling failures (the latter is probably just a precision issue).

**Comment by bsipocz** [comment]
@embray - a bit unrelated question: If I run test on the modul level with ``--package=coordinates``, they run even though decorated with ``@pytest.mark.skipif(str('not HAS_SCIPY'))`` where ``HAS_SCIPY`` is False. However they got skipped when I run them individually with ``-t``. 
Does the decorator have a memory from previously run test files?

```
try:
    import scipy
    if version.LooseVersion(scipy.__version__) > version.LooseVersion('0.12.0'):
        HAS_SCIPY = True
    else:
        HAS_SCIPY = False
except ImportError:
    HAS_SCIPY = False
```

Could you please point me where I do it wrong? I remember a similar issue a few month ago when the ``-t`` behaved differently, but can't find it now.

**Comment by astrofrog** [comment]
@bsipocz - what if you do:

```
python setup.py test -P coordinates
```

? We don't really support running tests with ``py.test`` directly.

**Comment by bsipocz** [comment]
Yes, that's what I'm doing. 
``python setup.py test --package=coordinates``

Would it be the case that the decorator acts as a lazyproperty, thus doesn't get updated? Anyway, now I think it's cleaner to define a new separate ``OLD_SCIPY`` and decorate the tests with that one, too.

**Comment by taldcroft** [comment]
We run astropy on 32-bit systems (used in Chandra flight ops) so my vote is to maintain support for as long as practical.

**Comment by migueldvb** [comment]
I think that the error about the float128 data type not understood can be fixed by replacing float128 by `np.longfloat` that is an alas to float128 on 64-bit and float96 on 32-bit, or by checking the bitness using the `sys.maxsize` attribute.

**Comment by embray** [comment]
Well, #3397 should address the one `modeling` failure.  But weirdly I can't reproduce the FITS failures.  Going to investigate a bit more...

**Comment by embray** [comment]
Oh, nevermind.  I see what it is.  It's not a 32-bit issue, it's because you have Python 2.7.3.  This was a bug in 2.7.3 that was fixed in 2.7.4.  I don't know if I brought this up with anyone else last time I encountered it, or if I just unilaterally decided we wouldn't support 2.7.3.  Hmm....  might be worth having a workaround for?

**Comment by olebole** [comment]
I found just one error and three failures on i386:

* `TypeError: data type "float128" not understood` (as above) (also on armel, armhf, mipsel)

* `test_eloc_attributes`:
```
    def test_eloc_attributes():
        from .. import AltAz, ITRS, GCRS, EarthLocation
    
        el = EarthLocation(lon=12.3*u.deg, lat=45.6*u.deg, height=1*u.km)
        it = ITRS(representation.SphericalRepresentation(lon=12.3*u.deg, lat=45.6*u.deg, distance=1*u.km))
        gc = GCRS(ra=12.3*u.deg, dec=45.6*u.deg, distance=6375*u.km)
    
        el1 = AltAz(location=el).location
        assert isinstance(el1, EarthLocation)
        assert el1.latitude == el.latitude
        assert el1.longitude == el.longitude
        assert el1.height == el.height
    
        el2 = AltAz(location=it).location
        assert isinstance(el2, EarthLocation)
        assert el2.latitude != it.spherical.lat
>       assert el2.longitude != it.spherical.lon
E       assert <Longitude [ 12.3] deg> != <Longitude 12.3 deg>
E        +  where <Longitude [ 12.3] deg> = <EarthLocation [(0.6836029704431764, 0.14904955169200265, 0.7144726796328034)] km>.longitude
E        +  and   <Longitude 12.3 deg> = <SphericalRepresentation lon=12.3 deg, lat=45.6 deg, distance=1.0 km>.lon
E        +    where <SphericalRepresentation lon=12.3 deg, lat=45.6 deg, distance=1.0 km> = <ITRS Coordinate (obstime=J2000.000): x=0.683602970443 km, y=0.149049551692 km, z=0.714472679633 km>.spherical
astropy/coordinates/tests/test_frames.py:531: AssertionError
```

* `test_identity` (also on arm64, powerpc, pp64el, s390x)

```
    def test_identity():
[...]
        assert_allclose((res_x, res_y),
                           (np.array([[-1.73205081, -1.73205081, -1.73205081],
                                      [-1.73205081, -1.73205081, -1.73205081]]),
                            np.array([[ 1.,  1.,  1.],
                                      [ 1.,  1.,  1.]])))
>       assert_allclose(model.inverse(res_x, res_y), (x, y))

astropy/modeling/tests/test_mappings.py:64: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

actual = array([[[ -2.97613496e-17,  -2.97613496e-17,  -2.97613496e-17],
        [ -2.9...0000000e+00],
        [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00]]])
desired = array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])
rtol = 1e-07, atol = 0, err_msg = '', verbose = True

    def assert_allclose(actual, desired, rtol=1e-7, atol=0,
                        err_msg='', verbose=True):
        """[...]"""
        import numpy as np
        def compare(x, y):
            return np.allclose(x, y, rtol=rtol, atol=atol)
    
        actual, desired = np.asanyarray(actual), np.asanyarray(desired)
        header = 'Not equal to tolerance rtol=%g, atol=%g' % (rtol, atol)
        assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
>                            verbose=verbose, header=header)

/usr/lib/python2.7/dist-packages/numpy/testing/utils.py:1183: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

comparison = <function compare at 0xf17aebc4>
x = array([[[ -2.97613496e-17,  -2.97613496e-17,  -2.97613496e-17],
        [ -2.9...0000000e+00],
        [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00]]])
y = array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])
err_msg = '', verbose = True
header = 'Not equal to tolerance rtol=1e-07, atol=0'

    def assert_array_compare(comparison, x, y, err_msg='', verbose=True,
                             header=''):
[...]
                if not cond :
>                   raise AssertionError(msg)
E                   AssertionError: 
E                   Not equal to tolerance rtol=1e-07, atol=0
E                   
E                   (mismatch 100.0%)
E                    x: array([[[ -2.97613496e-17,  -2.97613496e-17,  -2.97613496e-17],
E                           [ -2.97613496e-17,  -2.97613496e-17,  -2.97613496e-17]],
E                   ...
E                    y: array([[[ 0.,  0.,  0.],
E                           [ 0.,  0.,  0.]],
E                   ...

/usr/lib/python2.7/dist-packages/numpy/testing/utils.py:644: AssertionError
```

* `[doctest] astropy.wcs.wcs.WCS.all_world2pix` (also on arm64, powerpc, ppc64el, s390x, ):
```
1944         ...
1945         NoConvergence: 'WCS.all_world2pix' failed to converge to the
1946         requested accuracy. After 3 iterations, the solution is
1947         diverging at least for one input point.
1948 
1949         >>> # Now try to use some diverging data:
1950         >>> divradec = w.all_pix2world([[1.0, 1.0],
1951         ...                             [10000.0, 50000.0],
1952         ...                             [3.0, 1.0]], 1)
1953         >>> print(divradec)
Expected:
    [ 0.99999996  0.99999997  0.99999997]
Got:
    [ 0.99999997  0.99999997  0.99999997]

astropy/wcs/wcs.py:1953: DocTestFailure
```
which all looks not really complicated. They seem all not 32-bit related (except the errors), but appear on different 64-bit platforms as well.

Some platforms have more failures; I'll open new issues for them.
All build logs [here](https://buildd.debian.org/status/logs.php?pkg=python-astropy&ver=1.0~rc1-1)

**Comment by astrofrog** [comment]
I think the ``float128`` issues was fixed in https://github.com/astropy/astropy/commit/aa4fed256a64867f633f3c1098dce1b98058ea72

**Comment by bsipocz** [comment]
I've tried to fix the wcs doctest fails (the listed one is only the first, basically all the print statements are failing), but somehow the ``+FLOAT_CMP`` didn't work well with the lines that print out an array. 
@embray - is ``FLOAT_CMP`` supposed to work with arrays of (3, 2) shape?

**Comment by olebole** [comment]
@astrofrog I still didn't apply this. next round...

**Comment by olebole** [comment]
@astrofrog With aa4fed256a64867f633f3c1098dce1b98058ea72 the `float128` issue goes away (just tested on Debian Hurd); the other problems remain ofcourse.

**Comment by astrofrog** [comment]
The ``TypeError: 'buffer' does not have the buffer interface`` error is still occurring, but I don't see any other failures, when testing on Ubuntu 12.04 32-bit.

**Comment by astrofrog** [comment]
I have a suggested fix for the buffer error: https://github.com/astropy/astropy/pull/5078

**Comment by pllim** [comment]
Now that #5078 is merged, can we close this?

**Comment by olebole** [comment]
I just tested with 1.3rc1, and can confirm that this is OK now, including the `WCS.all_world2pix` doctest.

**Comment by mhvk** [comment]
@olebole -thanks for testing! I'll close this now it is confirmed to work.
