### ISSUE TITLE
"Exception TypeError ... ignored" when using astropy.io.fits.getdata() in astropy/1.1.2

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#4912]
Data obtained from an `astropy.io.fits.getdata()` call throws an ignored exception when the script is shut down.  For example:

```
Exception TypeError: "'NoneType' object is not callable" in <bound method FITS_rec.__del__ of FITS_rec([({some data}], dtype=(numpy.record, [{some types that are only integers & floats}]))> ignored
```

The immediate cause of the exception being *ignored* [is well known](https://docs.python.org/2/reference/datamodel.html#object.__del__).  The concern is that this appears in 1.1.2 but not 1.1.1, and only for FITS_rec objects returned by `astropy.io.fits.getdata()`.

Is it possible that #520 or #4539 changed the order in which objects are garbage collected or otherwise deleted such that garbage collection at script shutdown time tries to reference an object that no longer exists?

For completeness, this message appears with python/2.7.11, numpy/1.10.4 *or* numpy/1.11.0, astropy/1.1.2.

**Comment by pllim** [comment]
@taldcroft and @embray wrote those PRs. Perhaps they can comment?

**Comment by embray** [comment]
Would this also be fixed by #4694?

**Comment by weaverba137** [comment]
Indeed, this sounds similar to #4690, which #4694 is supposed to fix.

**Comment by pllim** [comment]
@weaverba137 , you can try installing the branch associated with that PR and confirm for yourself, if you wish. If that is indeed the case, I think we can close this?

**Comment by weaverba137** [comment]
I'm a little busy this week, but I'll try that test as soon as I can.

**Comment by pllim** [comment]
I am seeing the same thing still, but for a different project. Looks like #4694 did not fix this. After all, that PR only addressed `AttributeError`.

**Comment by embray** [comment]
Hard to say exactly where this is coming from without a traceback.  I haven't been able to reproduce it but I'll try.  Based on the message I think the only place where it *might* be coming from is the loop over the `self._col_weakrefs` `WeakSet`, since that's the only place in that `__del__` where an object might be called that could become `None` (I would consider that a bug in `WeakSet` but that's another story).

I'll try a it more to reproduce but somewhere it will be necessary maybe to put in a big catch all try/except.  Implementing a `__del__` that does anything non-trivial is always risky business, and I was very hesitant to do so, but unfortunately backed into a corner in this case.

**Comment by embray** [comment]
@weaverba137 Do you have a script that reproduces this reliably?  I can't reproduce this on Python 3 at all.  I will try Python 2 later but I don't have a Python 2 install on hand right now.

**Comment by pllim** [comment]
For my case, it is spurious, therefore I cannot provide something that can reproduce this reliably. But if I see it again, I'll investigate.

**Comment by pllim** [comment]
Potential fix in #4977
