### ISSUE TITLE
2.0rc1: UnicodeDecodeError when documentation built with Python3

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#6323]
When running `python3 setup.py build_docs`, I get the following error:
```
python3 setup.py build_docs
running build_docs
creating /build/python-astropy-2.0~rc1/docs/_build
creating /build/python-astropy-2.0~rc1/docs/_build/doctrees
creating /build/python-astropy-2.0~rc1/docs/_build/html
running build
running build_py
running pre_hook from astropy._erfa.setup_package for build_py command
running pre_hook from astropy.modeling.setup_package for build_py command
running build_ext
running pre_hook from astropy._erfa.setup_package for build_ext command
running pre_hook from astropy.modeling.setup_package for build_ext command
building 'astropy._compiler' extension
gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -O2 -fdebug-prefix-map=/build/python-astropy-2.0~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c astropy/_compiler.c -o build/temp.linux-x86_64-3.5/astropy/_compiler.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -O2 -fdebug-prefix-map=/build/python-astropy-2.0~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/astropy/_compiler.o -o build/lib.linux-x86_64-3.5/astropy/_compiler.cpython-35m-x86_64-linux-gnu.so
Running Sphinx v1.4.9
WARNING: The sphinx_gallery extension is not installed, so the gallery will not be built.  You will probably see additional warnings about undefined references due to this.
loading pickled environment... not yet created
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
WARNING: intersphinx inventory 'http://ipython.readthedocs.io/en/stable/objects.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 111] Connection refused>
[...]
WARNING: intersphinx inventory 'http://data.astropy.org/intersphinx/numpy.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 111] Connection refused>
[autosummary] generating autosummary for: analytic_functions/index.rst, changelog.rst, config/config_0_4_transition.rst, config/index.rst, constants/index.rst, convolution/index.rst, convolution/kernels.rst, convolution/non_normalized_kernels.rst, convolution/using.rst, coordinates/angles.rst, ..., whatsnew/0.1.rst, whatsnew/0.2.rst, whatsnew/0.3.rst, whatsnew/0.4.rst, whatsnew/1.0.rst, whatsnew/1.1.rst, whatsnew/1.2.rst, whatsnew/1.3.rst, whatsnew/2.0.rst, whatsnew/index.rst
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 250, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 322, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 407: ordinal not in range(128)
Sphinx Documentation subprocess failed with return code 1
```

**Comment by bsipocz** [comment]
This looks very similar to https://github.com/astropy/sphinx-automodapi/issues/28 in terms that both have issues in ``automodsumm_to_autosummary_lines``. 

cc @astrofrog as it's most probably needs to be addressed in ``sphinx-automodapi`` and the bundled over into ``astropy-helpers``.

@olebole - Out of curiosity, do you see this failure when using a never sphinx? (I would guess yes, but it's worth checking)

**Comment by astrofrog** [comment]
Working on a fix in sphinx-automodapi

**Comment by bsipocz** [comment]
@astrofrog - The fix is merged now, should we close this?

**Comment by pllim** [comment]
This might still a problem in `sphinx-gallery` even it is fixed in `automodapi`. Best to run it again to be sure before closing.

**Comment by astrofrog** [comment]
Yeah let's wait until we know for sure this fixes the docs build in astropy master before closing.

**Comment by eteq** [comment]
#6332 showed that this fixes the *immediate* problem in `automodsumm`, but there's still a problem in `sphinx-gallery` that fails at a later stage.  Ambiguous whether we want to leave this open and create a new one for the `sphinx-gallery` problem after merging in the new helpers...?
