### ISSUE TITLE
Consider using a robots.txt file to prevent search engines from indexing old docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7794]
According to https://github.com/rtfd/readthedocs.org/issues/2430 we should be able to use robots.txt

**Comment by pllim** [comment]
Why is this not a PR? 😉 😉 😉

**Comment by astrofrog** [comment]
I don't actually know much about robots.txt files other than they exist 😉 I also am not 100% sure how this works for already published versions, i.e. do we need to go and add a robots.txt file to the branches for all already published versions/tags?

**Comment by pllim** [comment]
There used to be a "domain expert" label but we removed it, so I added a "sprint" label instead. Sounds like a good issue for Hacktoberfest that is coming up.

**Comment by bsipocz** [comment]
as I recall we never actually created a `domain expert` label, but brainstormed about how to label these kind of issues. Adding hacktoberfest is actually quite a good idea, I was thinking about pitching astropy to non astronomy crowds.

**Comment by pllim** [comment]
Okay, I created the label. 🤞

**Comment by Hackhard** [comment]
I would love to take on this issue as part of hacktoberfest 2018.

**Comment by dasdachs** [comment]
Here's my [pull request](https://github.com/astropy/astropy/pull/7874) for this issue.

**Comment by Celebrimbor-forge** [comment]
Add another 'assignment' readme example

**Comment by pllim** [comment]
Seems like this is already resolved by #7874 ? Thanks, @dasdachs !

**Comment by good-praxis** [comment]
If it has been solved, why not close the issue? :stuck_out_tongue_winking_eye:

**Comment by bsipocz** [comment]
well, the issue has been resolved partially only, thus we keep it open.

**Comment by breofca** [comment]
@bsipocz could you elaborate?

**Comment by pllim** [comment]
> has been resolved partially

To elaborate, we are waiting for upstream fix over at RTD. I'll update the labels. Sorry for the confusion and thank you for your interest (feel free to look at other "good first issues" if you wish to contribute).

**Comment by astrofrog** [comment]
@breofca @good-praxis - see my comment in https://github.com/rtfd/readthedocs.org/issues/3161#issuecomment-431073144 - while #7874 might work going forward, it doesn't solve the problem that all the existing tagged versions (e.g. v1.0) don't have these meta tags and we'd need to re-tag all the versions (which we won't do).

**Comment by astrofrog** [comment]
I think we don't really need to do this anymore since we use noindex which appears to work well, so I'm going to close this.

**Comment by astrofrog** [comment]
I'm re-opening this because it's now (or will soon be) possible to add a robots.txt file, so we should probably do that too: https://docs.readthedocs.io/en/latest/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs

**Comment by astrofrog** [comment]
@dasdachs - yes please, that would be great. Thanks!

**Comment by dasdachs** [comment]
Sorry for the long wait. A added `robots.txt` and removed the `<meta>` tags workaround.

Pull request #8383

**Comment by saimn** [comment]
Closed by #8383.
