### ISSUE TITLE
Inconsistency behavior in APE14 WCS API implementations

### ISSUE THREAD

**Issue by nmearl** [astropy/astropy#9647]
### Description
This issue encompasses a few problems that have cropped up when interfacing with the WCS API wrapper classes (and presumably the APE14 API implementations in GWCS and FITS WCS).

The first issue is in pixel to world values transformation for a sliced wcs (e.g. a wcs wrapped with `SlicedLowLevelWCS` object:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-ccda0c3ea9df> in <module>
----> 1 print(arr_sliced.wcs.pixel_to_world([1, 2]))

~/projects/astropy/astropy/wcs/wcsapi/high_level_api.py in pixel_to_world(self, *pixel_arrays)
    213 
    214         # Compute the world coordinate values
--> 215         world = self.low_level_wcs.pixel_to_world_values(*pixel_arrays)
    216 
    217         if self.world_n_dim == 1:

~/projects/astropy/astropy/wcs/wcsapi/sliced_low_level_wcs.py in pixel_to_world_values(self, *pixel_arrays)
    160                 ipix_curr += 1
    161                 if self._slices_pixel[ipix].start is not None:
--> 162                     pixel_arrays_new.append(pixel_arrays[ipix_curr] + self._slices_pixel[ipix].start)
    163                 else:
    164                     pixel_arrays_new.append(pixel_arrays[ipix_curr])

TypeError: can only concatenate list (not "int") to list
```

It looks to be that it tries to concatenate a `list` and `int` when the pixel values are not passed as an ndarray. Replacing line 162 with

```
pixel_arrays_new.append(list(np.array(pixel_arrays[ipix_curr]) + self._slices_pixel[ipix].start))
```

fixes this issue (presuming that we would want to add the start of slice as an offset to the pixel values).

The second and third problems are a bit more nuanced and have to do with the implementation of `pixel_to_world_values` in GWCS and FITS WCS.

The `pixel_to_world_values` on a gwcs and fits wcs object return different things. For gwcs, it returns a list with a single ndarray containing the world values (e.g. `[array([1, 2])]`), while in fits wcs, it returns just the ndarray (e.g. `array([1, 2])`). This seems to be important because when `SlicedLowLevelWCS` is initialized the pixel dimensions (and world dimensions) to be kept are calculated based on the correlation matrices. In the case of a 1d array wcs, it's just the 0th dimension. This `world_keep` value is applied to the return value of the `pixel_to_world_values` call; in the gwcs case, it correctly gets `array([1, 2])`, but for fits wcs, it returns 1.
Relatedly, applying the index for the kept pixel dimension is done inside a list comprehension, meaning that for gwcs the final returned world values are `[[1, 2]]`. For fits, this means `[1]`.

### Expected behavior
Sliced wcs objects behave consistently.

### Actual behavior
Sliced wcs objects do not behave consistently.

### Steps to Reproduce

The comparison between the gwcs and fits wcs behaviors is demonstrated in this [notebook](https://gist.github.com/nmearl/6ff8b2a239fa017b70bdcd2053b3248d).

### System Details
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
Scipy 1.1.0
astropy 4.1.dev27003

**Comment by pllim** [comment]
Eh... @Cadair , is this related to your #8546 ?

**Comment by Cadair** [comment]
There is quite a lot to unpack here.

Your first example with the traceback, looks to me like a real bug in SLLWCS. Not sure if @astrofrog has thoughts on that.

as for

> For gwcs, it returns a list with a single ndarray containing the world values (e.g. [array([1, 2])]), while in fits wcs, it returns just the ndarray (e.g. array([1, 2])). 

This looks like a gWCS bug to me, I think the agreement either in or around APE 14 is that the return value is different for singular coordinates, but I could be wrong on that as well. Which implies the misbehaving slicing is also a SLLWCS bug.

**Comment by pllim** [comment]
cc @nden since GWCS is involved.

**Comment by astrofrog** [comment]
@nmearl - can you provide minimal examples to reproduce the issues you are seeing?

**Comment by nmearl** [comment]
@astrofrog the linked gist shows a jupyter notebook that demonstrates the issues.

**Comment by astrofrog** [comment]
Yeah there are definitely some bugs here!

**Comment by Cadair** [comment]
> The pixel_to_world_values on a gwcs and fits wcs object return different things. For gwcs, it returns a list with a single ndarray containing the world values (e.g. [array([1, 2])]), while in fits wcs, it returns just the ndarray (e.g. array([1, 2])).

This is fixed in [this gWCS PR](https://github.com/spacetelescope/gwcs/pull/261/files#diff-061764b3c26814441de8c7de0594d765R70-R72) and validated with #9677

**Comment by Cadair** [comment]
This shouldn't have Close? on it, there are still issues here.

**Comment by Cadair** [comment]
@nmearl Please test all this and let me know if you find any more issues.

**Comment by nmearl** [comment]
@Cadair hmm, this doesn't seem to solve the issue of extra dimensions in the transformations using gwcs -- is this in one of the gwcs PR's?

**Comment by Cadair** [comment]
yeah https://github.com/spacetelescope/gwcs/pull/261 I think.
